platform :ios, '6.0'

pod 'TestFlightSDK'
pod 'DCIntrospect'
pod 'AFNetworking'
pod 'AFHTTPRequestOperationLogger'
pod 'ISO8601DateFormatter'
pod 'Cloudinary'
pod 'Mantle'

target :KiwiUnitTest, :exclusive => true do
  pod 'Kiwi'
end
