platform :ios, '6.0'

pod 'TestFlightSDK'
pod 'DCIntrospect'
pod 'AFNetworking', '1.3.2'
pod 'AFHTTPRequestOperationLogger'
pod 'ISO8601DateFormatter'
pod 'Cloudinary'
pod 'Mantle'
pod 'NoticeView'
pod 'ReactiveCocoa', '1.8.0'

target :KiwiUnitTest, :exclusive => true do
  pod 'Kiwi'
end
