platform :ios, '6.0'

pod 'TestFlightSDK'
pod 'DCIntrospect'
pod 'AFNetworking'
pod 'AFHTTPRequestOperationLogger'
pod 'ISO8601DateFormatter'
pod 'Cloudinary'
pod 'Mantle'
pod 'NoticeView'
pod 'ReactiveCocoa'
pod 'FDTake'

target :KiwiUnitTest, :exclusive => true do
  pod 'Kiwi'
end
